In [1]:
import numpy as np # import pakietu do obsługi wektorów, macierzy i innych operacji matematycznych
# dalej używane jest odniesienie np. wskazujące na użycie obiektów i metod z pakietu numpy
import math

In [2]:
# Wartość liczby pi
np.pi

3.141592653589793

In [3]:
# obliczanie pierwiastka z podanej liczby
np.sqrt(4)

2.0

In [4]:
# Dokumentacja dla arctan2
help(np.arctan2)

Help on ufunc:

arctan2 = <ufunc 'arctan2'>
    arctan2(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Element-wise arc tangent of ``x1/x2`` choosing the quadrant correctly.
    
    The quadrant (i.e., branch) is chosen so that ``arctan2(x1, x2)`` is
    the signed angle in radians between the ray ending at the origin and
    passing through the point (1,0), and the ray ending at the origin and
    passing through the point (`x2`, `x1`).  (Note the role reversal: the
    "`y`-coordinate" is the first function parameter, the "`x`-coordinate"
    is the second.)  By IEEE convention, this function is defined for
    `x2` = +/-0 and for either or both of `x1` and `x2` = +/-inf (see
    Notes for specific values).
    
    This function is not defined for complex-valued arguments; for the
    so-called argument of complex values, use `angle`.
    
    Parameters
    ----------
    x1 : array_like, real-valued
      

In [5]:
np.arctan2(4,4)

0.7853981633974483

In [6]:
np.arctan2(0,4)

0.0

In [7]:
np.arctan2(4,0)

1.5707963267948966

In [8]:
np.arctan2(-4,0)

-1.5707963267948966

In [9]:
np.arctan2(0,-4)

3.141592653589793

In [10]:
# Funkcja sinus. Argumentem wejściowym jest kąt w radianach.
alpha = math.radians(30) # konwersja stopni na radiany
np.sin(alpha)

0.49999999999999994

In [11]:
# Funkcja cosinus. Argumentem wejściowym jest kąt w radianach.
alpha = math.radians(60) # konwersja stopni na radiany
np.cos(alpha)

0.5000000000000001

In [12]:
# Utworzenie wektora składającego się z 3 elementów
a = np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
# Utworzenie macierzy o rozmiarze 3x2
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(A)
print(f"Rozmiar macierzy: {A.shape}")

[[1 2]
 [3 4]
 [5 6]]
Rozmiar macierzy: (3, 2)


In [14]:
# Utworzenie macierzy diagonalnej
Adiag = np.diag([1,2,3,4])
print(Adiag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [15]:
# Transpozycja macierzy A
np.transpose(A)

array([[1, 3, 5],
       [2, 4, 6]])

In [16]:
# Mnożenie macierzy
M1 = np.array([[1,0,0],
               [0,2,0],
               [0,0,3]])
M2 = np.array([[1,2,3],
               [3,4,5],
               [1,1,2]])
W = M1 @ M2  # operator mnożenia macierzy
print(W)

[[ 1  2  3]
 [ 6  8 10]
 [ 3  3  6]]


In [17]:
# Wyznaczenie macierzy pseudoinwersji Moore’a–Penrose’a macierzy B
B = np.array([[1,0],
               [0,2],
               [0,5]])
Bpinv = np.linalg.pinv(B)
print(Bpinv)

[[1.         0.         0.        ]
 [0.         0.06896552 0.17241379]]


In [18]:
# Wyznaczanie macierzy odwrotnej do macierzy B
B = np.array([[1,0,0],
               [0,2,0],
               [0,0,3]])

Binv = np.linalg.inv(B)
print(Binv)
print("Sprawdzenie:")
print(B @ Binv)

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
Sprawdzenie:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# konwersja danych z formatu numpy na listę. 
B = np.array([[1,0,0],
               [0,2,0],
               [0,0,3]])
B_lista = B.tolist()
print(f"Typ danych B: {type(B)}")
print(B)
print("\n")
print(f"Typ danych B_lista: {type(B_lista)}")
print(B_lista)

Typ danych B: <class 'numpy.ndarray'>
[[1 0 0]
 [0 2 0]
 [0 0 3]]


Typ danych B_lista: <class 'list'>
[[1, 0, 0], [0, 2, 0], [0, 0, 3]]
